-- 回收站表：结构与 import_order 一致，额外记录删除时间（可重复执行）
USE order_split_merge;

CREATE TABLE IF NOT EXISTS import_order_recycle_bin (
    system_no VARCHAR(20) NOT NULL PRIMARY KEY COMMENT '系统编号（10位雪花ID，主键）',
    task_id BIGINT NOT NULL COMMENT '分单任务ID，关联 process_task.id',
    merchant VARCHAR(128) NOT NULL COMMENT '商家',
    merchant_split TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否已执行按商家分单',
    platform VARCHAR(128) COMMENT '导入时匹配的平台模板',
    order_no VARCHAR(64) COMMENT '订单编号',
    product_name VARCHAR(255) COMMENT '名称',
    spec VARCHAR(128) COMMENT '规格',
    quantity INT COMMENT '数量',
    receiver VARCHAR(64) COMMENT '收货人',
    address VARCHAR(512) COMMENT '收货地址',
    phone VARCHAR(32) COMMENT '手机号',
    shipping_fee DECIMAL(12, 2) COMMENT '运费',
    remark VARCHAR(512) COMMENT '备注',
    cost_price DECIMAL(12, 2) COMMENT '成本价',
    supply_price DECIMAL(12, 2) COMMENT '供货价',
    receipt_status VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '回单状态',
    logistics_no VARCHAR(128) COMMENT '物流单号',
    logistics_company VARCHAR(128) COMMENT '物流公司',
    after_sales TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否需售后',
    after_sales_remark VARCHAR(512) COMMENT '售后原因备注',
    after_sales_at DATETIME COMMENT '标记售后时间',
    after_sales_status VARCHAR(20) NOT NULL DEFAULT 'NONE' COMMENT '售后状态',
    issue_date DATETIME NOT NULL COMMENT '发单日期',
    source_row_num INT COMMENT 'Excel原始行号',
    created_at DATETIME NOT NULL COMMENT '入库时间',
    deleted_at DATETIME NOT NULL COMMENT '移入回收站时间',
    INDEX idx_import_order_recycle_bin_task_id (task_id),
    INDEX idx_import_order_recycle_bin_merchant (merchant),
    INDEX idx_import_order_recycle_bin_platform (platform),
    INDEX idx_import_order_recycle_bin_issue_date (issue_date),
    INDEX idx_import_order_recycle_bin_deleted_at (deleted_at),
    INDEX idx_import_order_recycle_bin_receipt_status (receipt_status),
    INDEX idx_import_order_recycle_bin_after_sales (after_sales),
    INDEX idx_import_order_recycle_bin_after_sales_status (after_sales_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='导入分单订单明细（回收站）';
